dgt:
  ap-id: MID-LX-DGT-02
  project-name: dgt-cloud-demo

spring:
  profiles:
    active: local

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, env, prometheus, metrics, httptrace, threaddump, heapdump, loggers
  metrics:
    export:
      prometheus:
        enabled: true